name: CI

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "./static/**"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "./static/**"
  pull_request_review:
  workflow_dispatch:


jobs:
  lmp-build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      
      # go
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16'
      
      - name: make lmp
        run: |
          cd eBPF_Visualization/eBPF_server
          make all
  
  sidecar-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
          cd eBPF_Supermarket/sidecar/
          go build -v ./...
      - name: Test
        run: |
          cd eBPF_Supermarket/sidecar/
          go test -v ./...
