name: dns_cache

on:
  push:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/ebpf_dns_cache/**'
      - '.github/workflows/dns_cache.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/ebpf_dns_cache/**'
      - '.github/workflows/dns_cache.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends clang libelf-dev zlib1g-dev make libbpf-dev git pkg-config 

      - name: Build
        run: |
          cd eBPF_Supermarket/ebpf_dns_cache
          cargo build

      - name: Clippy
        run: |
          cd eBPF_Supermarket/ebpf_dns_cache
          cargo clippy
