name: DDoS

on:
  push:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/old_project/eBPF_DDoS/**'
      - '.github/workflows/ebpf_ddos.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/old_project/eBPF_DDoS/**'
      - '.github/workflows/ebpf_ddos.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: test
      run: |
        cd eBPF_Supermarket/Network_Subsystem/old_project/eBPF_DDoS/bpf/dns-ddos
        make builder
        docker run -d -m 128m -v `pwd`/test/config:/etc/coredns --name dwq-coredns burkeazbill/docker-coredns -conf /etc/coredns/Corefile
        docker run --privileged -d --name dwq-ddos-test --network=container:dwq-coredns \
        -v /lib/modules:/lib/modules -v /usr/src:/usr/src -v /sys/kernel/debug:/sys/kernel/debug:rw \
        -v /sys/fs/bpf:/sys/fs/bpf -v `pwd`:/ddos bpf-builder \
        sh -c "mount -t bpf bpf /sys/fs/bpf && cd /ddos/src && make xdp_dns_kern && \
        ip link set dev eth0 xdpgeneric obj xdp_dns_kern.o sec xdp && \
        python3 -u catch_dns.py"
        for i in $(seq 1 11)
        do
        if [ $(docker logs dwq-ddos-test | grep 'started!') ]; then break; fi
        sleep 5
        done
        if [ $i -eq 11 ]; then exit 1; fi
