name: eBPF_proc_image

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/eBPF_proc_image/**'
      - '.github/workflows/eBPF_proc_image.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/eBPF_proc_image/**'
      - '.github/workflows/eBPF_proc_image.yml'

jobs:
  proc_image-project-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies and Init Env
        run: |
          sudo apt update
          sudo apt install libbpf-dev clang llvm libelf-dev libpcap-dev gcc-multilib build-essential
          git submodule update --init --recursive

      - name: Run lifecycle_image
        run: |
          cd eBPF_Supermarket/eBPF_proc_image
          make lifecycle_image
          sudo ./lifecycle_image -t 1

      - name: Run lock_image
        run: |
          cd eBPF_Supermarket/eBPF_proc_image
          make lock_image
          sudo ./lock_image -t 1
      
      - name: Run newlife_image
        run: |
          cd eBPF_Supermarket/eBPF_proc_image
          make newlife_image
          sudo ./newlife_image -t 1

      - name: Run keytime_image
        run: |
          cd eBPF_Supermarket/eBPF_proc_image
          make keytime_image
          sudo ./keytime_image -t 1

      - name: Run proc_offcpu_time
        run: |
          cd eBPF_Supermarket/eBPF_proc_image/proc_offcpu_time
          make
          sudo ./proc_offcpu_time -t 1

      - name: Run mutex_test
        run: |
          cd eBPF_Supermarket/eBPF_proc_image/test
          sudo make
          sudo insmod mutex_test1.ko
          sudo insmod mutex_test2.ko

      - name: Run test_sleep
        run: |
          cd eBPF_Supermarket/eBPF_proc_image/test
          gcc test_sleep.c -o test_sleep
          ./test_sleep
      
      - name: Run test_proc
        run: |
          cd eBPF_Supermarket/eBPF_proc_image/test
          gcc test_proc.c -o test_proc
          ./test_proc
