name: Stack_Analyser

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/Stack_Analyser/**'
      - '.github/workflows/ebpf_stack_analyser.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Stack_Analyser/**'
      - '.github/workflows/ebpf_stack_analyser.yml'
      

jobs:
  libbpf-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install native lib dependencies
        run: |
          git submodule update --init --recursive
          sudo apt install clang libelf1 libelf-dev zlib1g-dev
        
      - name: Run app with native lib
        run: |
          cd eBPF_Supermarket/Stack_Analyser
          make
          sudo ./stack_analyzer on-cpu off-cpu mem io ra -t 5