name: XDP_libxdp

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/XDP_Res-Application/tools/xdp_ping/**'
      - '.github/workflows/ebpf_xdp_libxdp.yml'
      
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/XDP_Res-Application/tools/xdp_ping/**'
      - '.github/workflows/ebpf_xdp_libxdp.yml'
    
jobs:
  libbpf-libxdp-project-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies and Init Env
        run: |
          sudo apt install libbpf-dev clang llvm libelf-dev libpcap-dev gcc-multilib build-essential
          git submodule update --init --recursive

      - name: Build and Run
        run: |
          pushd ./
          cd eBPF_Supermarket/XDP_Res-Application/tools/
          make
          sudo ./xdp_ping/xdp_ping_user -d lo
          popd
