name: Test for ebpf_tcp_ping build and run

on:
  push:
    branches: [ "*" ]
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/eBPF_TCP_Ping/**'
      - '.github/workflows/ebpf_tcp_ping.yml'
  pull_request:
    branches: [ "*" ]
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/eBPF_TCP_Ping/**'
      - '.github/workflows/ebpf_tcp_ping.yml'

jobs:
  run-test:
    name: Build and run
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y bison build-essential flex curl libedit-dev \
          libllvm12 llvm-12-dev libclang-12-dev python python3 python3-distutils zlib1g-dev libelf-dev libfl-dev \
          bpfcc-tools linux-headers-$(uname -r) libelf-dev libpcap-dev gcc-multilib build-essential
        sudo ln -sf /usr/bin/llc-12 /usr/bin/llc

    - name: Cache bcc
      id: cache-bcc
      uses: actions/cache@v3
      with:
        path: bcc
        key: ${{ runner.os }}-bcc-0.24.0

    - name: Build bcc
      if: steps.cache-bcc.outputs.cache-hit != 'true'
      run: |
        git clone -b v0.24.0 https://github.com/iovisor/bcc.git
        export LLVM_ROOT="/usr/lib/llvm-12"
        mkdir bcc/build; cd bcc/build
        cmake ..
        make -j2

    - name: Install bcc
      run: |
        cd bcc/build
        sudo make install

    - name: Compile and install xdp
      run: |
        cd eBPF_Supermarket/eBPF_TCP_Ping
        make && sudo make install

    - name: Test run ebpf ping
      run: |
        cd eBPF_Supermarket/eBPF_TCP_Ping
        go build -o tcp_ping tcp_ping.go
        # help
        ./tcp_ping -h
        # sudo ./telescope 127.0.0.1
        sudo timeout -s SIGINT 20 ./tcp_ping 127.0.0.1 || pwd
