name: kvm_watcher

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/kvm_watcher/**'
      - '.github/workflows/kvm_watcher.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/kvm_watcher/**'
      - '.github/workflows/kvm_watcher.yml'

jobs:
  kvm_watcher-project-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install clang libelf1 libelf-dev zlib1g-dev
          sudo apt install libbpf-dev
          sudo apt install linux-tools-$(uname -r)
          sudo apt install linux-cloud-tools-$(uname -r)
      - name: Load KVM mod
        run: |   
          sudo modprobe kvm && sudo modprobe kvm-intel
      - name: Run kvm_watcher
        run: |
          cd eBPF_Supermarket/kvm_watcher/
          make
          sudo ./kvm_watcher -w -t 5
          sudo ./kvm_watcher -e -t 5 -s
          sudo ./kvm_watcher -n -t 5 
          sudo ./kvm_watcher -d -t 5 
          sudo ./kvm_watcher -f -t 5
          make clean

