name: paf

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/Memory_Subsystem/old_project//paf/**'
      - '.github/workflows/Memory_Subsystem__paf.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Memory_Subsystem/old_project//paf/**'
      - '.github/workflows/Memory_Subsystem__paf.yml'

jobs:
  paf-project-build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libbpf-dev clang llvm libelf-dev libpcap-dev gcc-multilib build-essential linux-tools-$(uname -r)
          git submodule update --init --recursive

      - name: Run paf
        continue-on-error: true
        run: |
          cd eBPF_Supermarket/Memory_Subsystem/old_project//paf/
          bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
          make paf
          sudo timeout 20 ./paf
